repo:
  add-topic:
    - terraform
    - azure
    - azurerm-container-registry
  default-branch: main
  description: "A Terraform module that manages the container resources from the azurerm provider."
  homepage: https://t-systems-mms.github.io/
  visibility: public
