---
name: github

on:
  schedule:
    - cron: '00 10 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/settings.json'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: gh cli
        run: |
          TOPICS=$(jq '(.repos.topics) | .[]' ${SETTINGS})
          for TOPIC in ${TOPICS}; do gh repo edit --add-topic ${TOPIC}; done
        env:
          SETTINGS: .github/settings.json
          GH_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
