---
name: github

on:
  schedule:
    - cron: '00 10 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/settings.yaml'

jobs:
  call-github:
    uses: T-Systems-MMS/.github/.github/workflows/github.yml@github_settings
    secrets:
      GH_CLI_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
